version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=videodetector
      - POSTGRES_USER=videodetector
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.12.6-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=videodetector
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
volumes:
  db:
    driver: local
