version: "3.8"
services:
  gateway:
    build: gateway/
    ports:
      - 8090:8090
    depends_on:
      - server
  server:
    build: backend/
    ports:
      - 8080:8080
    volumes:
      - ./volumes/server:/storage
    depends_on:
      - db
      - liquibase
      - rabbitmq
      - ml
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
  transcription:
    build: audio-transcript/
    volumes:
      - ./volumes/server:/storage
    depends_on:
      - db
      - liquibase
      - rabbitmq
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_HOST=${RABBITMQ_DEFAULT_HOST}
      - QUEUE_IN_NAME=${QUEUE_IN_NAME}
      - QUEUE_OUT_NAME=${QUEUE_OUT_NAME}
      - EXCHANGE_NAME=${EXCHANGE_NAME}
      - ROUTUNG_KEY_IN=${ROUTUNG_KEY_IN}
      - ROUTING_KEY_OUT=${ROUTING_KEY_OUT}
      - MODEL_SIZE=${MODEL_SIZE}
      - DEVICE=${DEVICE}
      - COMPUTE_TYPE=${COMPUTE_TYPE}
      - BEAM_SIZE=${BEAM_SIZE}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all
  callback:
    build: caller-log/
    ports:
      - 8091:8091
    depends_on:
      - db
      - liquibase
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  liquibase:
    build: liquibase/
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  rabbitmq:
    image: rabbitmq:3.12.6-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  ml:
    image: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
    shm_size: "8gb"
    command: nvidia-smi
    volumes:
      - ./volumes/server:/storage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]